### PR TITLE
show snack bar once we delete any todo

### PR DESCRIPTION
**Pull request by pavankalyan-codes**

### CODE REVIEW

**Comment by pavankalyan-codes** [comment]
#28 Raised a PR for this feature. Pls, merge the PR if everything looks fine on review. Thanks.

**Comment by pavankalyan-codes** [comment]
Addressed review comments. Please verify changes and merge if everything looks fine on review. Thanks.

**Comment by nirajacharyaa** [comment]
Great job, you have done. Keep contributing.

**Comment by nirajacharyaa** [comment]
This closes the issue #17 .

**Pull request merged**
